### ISSUE TITLE
Publish logmatic-js on NPM

### ISSUE THREAD

**Issue by mickaeltr** [logmatic/logmatic-js#3]
Hello,
It would be very useful to have logmatic-js available on NPM (https://www.npmjs.com/)
Here is some documentation about publishing on NPM: https://docs.npmjs.com/getting-started/publishing-npm-packages
Thanks

**Comment by egueidan** [comment]
Hello Mickaël,
  thanks for your feedback. Publishing on NPM is on our todo list. We'll look into it very soon.
Regards

**Comment by renaudboutet** [comment]
Hi Mickaël,

We did it a couple of days ago. Thanks again for pinging us.

Regards
