### ISSUE TITLE
Alternative to logmatic-js (at Datadog)?

### ISSUE THREAD

**Issue by mickaeltr** [logmatic/logmatic-js#30]
Hello,

I used to be a very happy Logmatic user. I liked its ability to easily aggregate both my backend and frontend logs. I do have that requirement again. Since then, Logmatic was acquired by Datadog, which only seems to offer server-side logs aggregation (along with some monitoring things that I might not need). Any suggestion is welcome…

Thanks (and sorry for the rather inappropriate channel I used for that question)

**Comment by HugoCrd** [comment]
We tweaked logmatic-js a little to send our events to Datadog using their HTTP Intake endpoint:
`https://http-intake.logs.datadoghq.com/v1/input/<DATADOG_API_KEY>`

Works like a charm.

src: https://docs.datadoghq.com/api/?lang=bash#logs

**Comment by mickaeltr** [comment]
Looks like we're going to try to achieve that with our ELK, using [Logstash HTTP input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html). Thanks @HugoCrd

**Comment by mickaeltr** [comment]
It seems that Datadog is now offering this feature: https://www.datadoghq.com/blog/monitor-javascript-console-logs/
